[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build --filter=backend"

[deploy]
startCommand = "pnpm --filter=backend start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"